-- ============================================================
-- TABLD — Seed Curated Sample Restaurants for Chennai
-- Safe to run multiple times: uses ON CONFLICT (slug) DO NOTHING
-- Your existing restaurants will NOT be modified or deleted.
-- ============================================================

INSERT INTO public.restaurants (
  name,
  slug,
  cuisine,
  cuisine_category,
  price_range,
  price_level,
  editorial_description,
  short_description,
  address,
  city,
  phone,
  email,
  website,
  cover_image,
  gallery,
  menu,
  best_dishes,
  hours,
  accessibility,
  noise_level,
  noise_level_score,
  vibe_tags,
  ambience,
  cuisine_filters,
  budget_filter,
  distance_km,
  featured,
  trending,
  recently_added,
  approved,
  rating,
  review_count,
  capacity,
  available_slots
)
VALUES
(
  'Avartana',
  'avartana-chennai',
  'Modern South Indian',
  'South Indian',
  '₹₹₹₹',
  4,
  'A culinary tour de force reimagining coastal and southern Indian flavours through avant-garde techniques, modernist presentations, and sublime tasting menus.',
  'Progressive, Michelin-caliber South Indian degustation menus.',
  'ITC Grand Chola, 63 Anna Salai, Guindy',
  'Chennai',
  '+91 44 2220 0000',
  'avartana.itcgrandchola@itchotels.in',
  'https://www.itchotels.com/in/en/itcgrandchola-chennai/dining/avartana',
  'https://images.unsplash.com/photo-1544025162-d76694265947?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80'],
  '[{"section":"Tasting Menu Highlights","items":[{"name":"Distilled Rasam","description":"Infused with fresh coriander and crushed Tellicherry black pepper","price":"₹850"},{"name":"Pan-Seared Lobster","description":"Tossed in roasted shallots and tender coconut emulsion","price":"₹1,850"},{"name":"Asparagus & Raw Mango","description":"Steamed dumplings with spiced coconut foam","price":"₹950"},{"name":"Lamb Chops Ghee Roast","description":"Slow-roasted tender lamb chops with Byadgi chili glaze","price":"₹1,950"}]}]'::jsonb,
  ARRAY['Distilled Rasam', 'Lamb Chops Ghee Roast', 'Pan-Seared Lobster'],
  '{"monday":{"open":"19:00","close":"23:30","closed":false},"tuesday":{"open":"19:00","close":"23:30","closed":false},"wednesday":{"open":"19:00","close":"23:30","closed":false},"thursday":{"open":"19:00","close":"23:30","closed":false},"friday":{"open":"19:00","close":"23:30","closed":false},"saturday":{"open":"12:30","close":"23:30","closed":false},"sunday":{"open":"12:30","close":"23:30","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":true,"hearingLoop":true,"largeText":true,"note":"Full valet and elevator access from ITC lobby."}'::jsonb,
  'Quiet',
  1,
  ARRAY['Fine Dining', 'Romantic', 'Modern Indian', 'Luxury'],
  'Luxury',
  ARRAY['South Indian', 'Modern Indian', 'Fine Dining'],
  '₹₹₹₹',
  4.2,
  true,
  true,
  false,
  true,
  4.9,
  342,
  45,
  ARRAY['19:00','19:30','20:00','20:30','21:00','21:30']
),
(
  'Pumpkin Tales',
  'pumpkin-tales-alwarpet',
  'Global Comfort & Brunch',
  'Cafe & Brunch',
  '₹₹',
  2,
  'An all-day cafe celebrated for artisanal sourdough toasts, vibrant grain bowls, Japanese souffle pancakes, and exceptional specialty pour-over coffees.',
  'Wholesome global comfort food & artisan bakery.',
  '37, 20 Bheemanna Garden Street, Alwarpet',
  'Chennai',
  '+91 44 2499 6945',
  'hello@pumpkintales.com',
  'https://www.pumpkintales.com',
  'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80', 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&q=80'],
  '[{"section":"All-Day Breakfast & Mains","items":[{"name":"Avocado & Poached Egg Toast","description":"Hass avocado, sourdough bread, zaatar, pickled radish","price":"₹480"},{"name":"Japanese Souffle Pancakes","description":"Light-as-air stack with maple honeycomb butter","price":"₹420"},{"name":"Korean Bibimbap Bowl","description":"Sticky rice, sauteed seasonal greens, gochujang sauce","price":"₹560"},{"name":"Truffle Mushroom Risotto","description":"Arborio rice, wild shiitake, parmesan crisp","price":"₹620"}]}]'::jsonb,
  ARRAY['Avocado & Poached Egg Toast', 'Japanese Souffle Pancakes', 'Truffle Mushroom Risotto'],
  '{"monday":{"open":"07:00","close":"22:30","closed":false},"tuesday":{"open":"07:00","close":"22:30","closed":false},"wednesday":{"open":"07:00","close":"22:30","closed":false},"thursday":{"open":"07:00","close":"22:30","closed":false},"friday":{"open":"07:00","close":"22:30","closed":false},"saturday":{"open":"07:00","close":"23:00","closed":false},"sunday":{"open":"07:00","close":"23:00","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":false,"hearingLoop":false,"largeText":false,"note":"Ramp available at main entrance."}'::jsonb,
  'Moderate',
  2,
  ARRAY['Brunch', 'Casual', 'Outdoor Seating', 'Coffee'],
  'Casual',
  ARRAY['Cafe & Brunch', 'Continental', 'Vegetarian-Friendly'],
  '₹₹',
  2.1,
  true,
  true,
  false,
  true,
  4.8,
  215,
  60,
  ARRAY['09:00','10:30','12:00','13:30','18:00','19:30','20:30']
),
(
  'Soy Soi',
  'soy-soi-adyar',
  'Pan-Asian & Dim Sum',
  'Asian',
  '₹₹₹',
  3,
  'An homage to the street-food culture of Thailand, Vietnam, Singapore, and Indonesia, serving handcrafted dim sums, aromatic laksa, and sizzling robata grills.',
  'Authentic Southeast Asian street flavors & delicate dim sums.',
  '2/10 Gandhi Nagar 1st Main Road, Adyar',
  'Chennai',
  '+91 44 4553 4343',
  'reservations@soysoi.in',
  'https://www.soysoi.in',
  'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80', 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&q=80'],
  '[{"section":"Dim Sum & Asian Specialties","items":[{"name":"Truffle Edamame Dumplings","description":"Steamed crystal dumplings with black truffle oil","price":"₹520"},{"name":"Prawn Har Gau","description":"Classic translucent wrappers filled with juicy tiger prawns","price":"₹580"},{"name":"Singaporean Seafood Laksa","description":"Spicy coconut broth, rice noodles, calamari, tofu puffs","price":"₹690"},{"name":"Nasi Goreng Istimewa","description":"Indonesian wok-fried rice with chicken satay & fried egg","price":"₹640"}]}]'::jsonb,
  ARRAY['Truffle Edamame Dumplings', 'Singaporean Seafood Laksa', 'Prawn Har Gau'],
  '{"monday":{"open":"12:00","close":"23:00","closed":false},"tuesday":{"open":"12:00","close":"23:00","closed":false},"wednesday":{"open":"12:00","close":"23:00","closed":false},"thursday":{"open":"12:00","close":"23:00","closed":false},"friday":{"open":"12:00","close":"23:30","closed":false},"saturday":{"open":"12:00","close":"23:30","closed":false},"sunday":{"open":"12:00","close":"23:00","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":false,"hearingLoop":false,"largeText":false,"note":"Street-level entrance with elevator."}'::jsonb,
  'Lively',
  3,
  ARRAY['Pan-Asian', 'Dim Sum', 'Lively', 'Cocktails'],
  'Lively',
  ARRAY['Asian', 'Dim Sum', 'Thai', 'Vietnamese'],
  '₹₹₹',
  3.8,
  false,
  true,
  false,
  true,
  4.7,
  188,
  70,
  ARRAY['12:30','13:30','19:00','20:00','21:00','21:45']
),
(
  'The Flying Elephant',
  'the-flying-elephant-guindy',
  'Global Experiential & Grill',
  'Global',
  '₹₹₹₹',
  4,
  'A breathtaking multi-level architectural spectacle offering theatrical open show-kitchens, world-class wood-fired grills, and curated mixology.',
  'Multi-level theater of global dining & live kitchens.',
  'Park Hyatt Chennai, 39 Velachery Road, Guindy',
  'Chennai',
  '+91 44 7177 1234',
  'flyingelephant.parkhyatt@hyatt.com',
  'https://www.hyatt.com/en-US/hotel/india/park-hyatt-chennai/cheph/dining',
  'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80'],
  '[{"section":"Charcoal Grill & Global Signatures","items":[{"name":"Wood-Fired Neapolitan Pizza","description":"San Marzano tomatoes, fior di latte, fresh basil","price":"₹950"},{"name":"Australian Lamb Rack","description":"Herb-crusted with roasted root vegetables and jus","price":"₹2,400"},{"name":"Atlantic Salmon Steak","description":"Charred asparagus, saffron beurre blanc","price":"₹1,850"},{"name":"Molten Valrhona Chocolate Cake","description":"Madagascar vanilla bean gelato","price":"₹650"}]}]'::jsonb,
  ARRAY['Wood-Fired Neapolitan Pizza', 'Australian Lamb Rack', 'Atlantic Salmon Steak'],
  '{"monday":{"open":"19:00","close":"01:00","closed":false},"tuesday":{"open":"19:00","close":"01:00","closed":false},"wednesday":{"open":"19:00","close":"01:00","closed":false},"thursday":{"open":"19:00","close":"01:00","closed":false},"friday":{"open":"19:00","close":"02:00","closed":false},"saturday":{"open":"19:00","close":"02:00","closed":false},"sunday":{"open":"12:00","close":"01:00","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":false,"hearingLoop":true,"largeText":false,"note":"Full elevator connectivity between dining levels."}'::jsonb,
  'Lively',
  3,
  ARRAY['Nightlife', 'Luxury', 'Cocktails', 'Date Night'],
  'Luxury',
  ARRAY['Global', 'Italian', 'Grill', 'Fine Dining'],
  '₹₹₹₹',
  4.8,
  true,
  true,
  false,
  true,
  4.8,
  410,
  120,
  ARRAY['19:00','20:00','21:00','22:00','23:00']
),
(
  'Amethyst Café',
  'wild-garden-amethyst-royapettah',
  'Continental & European Bakery',
  'Cafe & Brunch',
  '₹₹',
  2,
  'Set within a lush colonial-era heritage mansion and courtyard garden, Amethyst is Chennais iconic haven for European pasta, artisanal quiches, and fragrant teas.',
  'Garden courtyard cafe in a restored colonial heritage bungalow.',
  'Whites Road, Royapettah',
  'Chennai',
  '+91 44 4599 1630',
  'contact@wildgardenamethyst.com',
  'https://www.amethystchennai.com',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80', 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80'],
  '[{"section":"Garden Kitchen Favorites","items":[{"name":"Spinach & Goat Cheese Quiche","description":"Served with balsamic vinaigrette dressed wild greens","price":"₹420"},{"name":"Penne Aglio Olio e Peperoncino","description":"Extra virgin olive oil, garlic slivers, sundried tomatoes","price":"₹490"},{"name":"Smoked Chicken Panini","description":"Brie cheese, caramelized onions, homemade ciabatta","price":"₹460"},{"name":"Warm Apple Crumble Tart","description":"Salted caramel drizzle, vanilla ice cream","price":"₹380"}]}]'::jsonb,
  ARRAY['Spinach & Goat Cheese Quiche', 'Smoked Chicken Panini', 'Warm Apple Crumble Tart'],
  '{"monday":{"open":"10:00","close":"23:00","closed":false},"tuesday":{"open":"10:00","close":"23:00","closed":false},"wednesday":{"open":"10:00","close":"23:00","closed":false},"thursday":{"open":"10:00","close":"23:00","closed":false},"friday":{"open":"10:00","close":"23:00","closed":false},"saturday":{"open":"10:00","close":"23:00","closed":false},"sunday":{"open":"10:00","close":"23:00","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":false,"hearingLoop":false,"largeText":false,"note":"Paved garden pathways and ground level seating."}'::jsonb,
  'Quiet',
  1,
  ARRAY['Romantic', 'Heritage', 'Outdoor Seating', 'Coffee'],
  'Romantic',
  ARRAY['Cafe & Brunch', 'Continental', 'Italian'],
  '₹₹',
  1.8,
  false,
  true,
  false,
  true,
  4.7,
  380,
  80,
  ARRAY['11:00','13:00','16:00','18:00','19:30','21:00']
),
(
  'Balfour Italian Eatery',
  'balfour-italian-kilpauk',
  'Authentic Italian & Pizza',
  'Italian',
  '₹₹₹',
  3,
  'Handcrafted Roman and Neapolitan pizzas baked in a custom stone oven, paired with fresh extruded pastas and decadent artisanal tiramisu.',
  'Artisanal stone-baked pizzas & fresh handmade pastas.',
  '24 Balfour Road, Kilpauk',
  'Chennai',
  '+91 44 4858 2424',
  'ciao@balfoureats.com',
  'https://www.balfoureats.com',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1920&q=80',
  ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80', 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=800&q=80'],
  '[{"section":"Pasta Fresca & Pizze","items":[{"name":"Burrata Pugliese Pizza","description":"Fresh burrata, heirloom cherry tomatoes, pesto drizzle","price":"₹780"},{"name":"Hand-rolled Tagliatelle Funghi","description":"Wild porcini mushroom sauce, parmigiano reggiano","price":"₹680"},{"name":"Gnocchi al Gorgonzola","description":"Potato gnocchi, cream of gorgonzola, roasted walnuts","price":"₹640"},{"name":"Classic Espresso Tiramisu","description":"Savoiardi ladyfingers, mascarpone, dusting of cocoa","price":"₹450"}]}]'::jsonb,
  ARRAY['Burrata Pugliese Pizza', 'Hand-rolled Tagliatelle Funghi', 'Classic Espresso Tiramisu'],
  '{"monday":{"open":"12:00","close":"23:00","closed":false},"tuesday":{"open":"12:00","close":"23:00","closed":false},"wednesday":{"open":"12:00","close":"23:00","closed":false},"thursday":{"open":"12:00","close":"23:00","closed":false},"friday":{"open":"12:00","close":"23:30","closed":false},"saturday":{"open":"12:00","close":"23:30","closed":false},"sunday":{"open":"12:00","close":"23:00","closed":false}}'::jsonb,
  '{"wheelchairAccess":true,"brailleMenu":false,"hearingLoop":false,"largeText":false,"note":"Street parking and wheelchair ramp available."}'::jsonb,
  'Moderate',
  2,
  ARRAY['Italian', 'Pizza', 'Casual Dining', 'Family'],
  'Casual',
  ARRAY['Italian', 'Pizza', 'European'],
  '₹₹₹',
  3.1,
  false,
  false,
  true,
  true,
  4.8,
  142,
  50,
  ARRAY['12:30','13:30','19:00','20:00','21:00','21:45']
)
ON CONFLICT (slug) DO NOTHING;
